# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

target 'Justwithin' do

  use_frameworks!

 	pod 'GTMOAuth2' , '1.1.5'
 	pod 'FBSDKCoreKit', '4.26.0'
 	pod 'Firebase' , '4.1.1'
 	pod 'FirebaseAuth' , '4.1.1'
 	pod 'FirebaseStorage' , '2.0.1'
 	pod 'FirebaseDatabase' , '4.0.2' 
end
